services:
  app:
    build: .
    container_name: go-lab-wsl
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    # Для разработки с автообновлением (опционально)
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - tmp/